// <auto-generated />
using AnuncioWebMotors.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnuncioWebMotors.Migrations
{
    [DbContext(typeof(AnuncioWebMotorsContext))]
    [Migration("20200609181636_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnuncioWebMotors.Models.Class_Anuncio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Observacao")
                        .IsRequired();

                    b.Property<int>("Quilometragem");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.HasKey("ID");

                    b.ToTable("tb_AnuncioWebmotors");
                });
#pragma warning restore 612, 618
        }
    }
}
